/**
 * Embedded Appium server lifecycle (ADR-0008, mechanism live-verified against
 * appium@3.5.2):
 *
 * SYNTHESIZED PROJECT-MODE HOME — we generate an APPIUM_HOME whose
 * package.json declares the EXACT appium+driver versions resolved from THIS
 * package's own dependency tree (lockfile-governed, ADR-0001 §5.10) and
 * symlink the resolved packages into its node_modules. Appium's project-mode
 * manifest auto-discovers them; no `appium driver install` ever runs
 * (`--source=local` is verified broken: it shells to `npm link`, which fires
 * the drivers' `prepare` scripts and fails on published tarballs).
 *
 * Live-verified hazards handled here:
 * - EADDRINUSE calls process.exit(1) even with throwInsteadOfExit → we
 *   allocate the port ourselves immediately before boot.
 * - main() installs its own SIGINT/SIGTERM handlers that process.exit(0) →
 *   we strip them so the Kraken CLI owns signals (ADR-0001 §5.11).
 */
import { mkdirSync, renameSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { createServer } from 'node:net';
import { dirname, join } from 'node:path';

import type { Logger } from '@kraken-e2e/contracts';
import { KrakenError } from '@kraken-e2e/contracts';

const require_ = createRequire(import.meta.url);

function resolvedPackage(name: string): { dir: string; version: string } {
  const packageJsonPath = require_.resolve(`${name}/package.json`);
  const { version } = require_(packageJsonPath) as { version: string };
  return { dir: dirname(packageJsonPath), version };
}

/**
 * Idempotent: refreshes symlinks every start (pnpm store paths move); version
 * bumps change the generated package.json, which changes its md5 and triggers
 * Appium's manifest re-sync.
 */
export function prepareAppiumHome(homeDir: string, driverPackages: readonly string[]): void {
  const nodeModules = join(homeDir, 'node_modules');
  mkdirSync(nodeModules, { recursive: true });

  const appium = resolvedPackage('appium');
  const dependencies: Record<string, string> = { appium: appium.version };

  for (const name of [...driverPackages, 'appium']) {
    const resolved = name === 'appium' ? appium : resolvedPackage(name);
    if (name !== 'appium') dependencies[name] = resolved.version;
    const linkPath = join(nodeModules, name);
    mkdirSync(dirname(linkPath), { recursive: true });
    // Concurrent-run-safe replace: symlink to a temp name, rename over the
    // target (atomic on POSIX) — a plain rm+symlink pair races a sibling run.
    const tempLink = `${linkPath}.tmp-${process.pid}`;
    rmSync(tempLink, { force: true });
    symlinkSync(resolved.dir, tempLink, 'dir');
    rmSync(linkPath, { recursive: true, force: true });
    renameSync(tempLink, linkPath);
  }

  writeFileSync(
    join(homeDir, 'package.json'),
    `${JSON.stringify(
      {
        name: 'kraken-appium-home',
        private: true,
        description: 'Generated by Kraken — appium project-mode home (ADR-0008). Do not edit.',
        dependencies,
      },
      null,
      2,
    )}\n`,
  );
}

/** Allocates an OS-assigned free port (hazard 1: appium dies on EADDRINUSE). */
export async function allocatePort(): Promise<number> {
  return new Promise((resolve, reject) => {
    const probe = createServer();
    probe.once('error', reject);
    probe.listen(0, '127.0.0.1', () => {
      const address = probe.address();
      const port = typeof address === 'object' && address !== null ? address.port : undefined;
      probe.close(() => {
        if (port === undefined) reject(new Error('could not allocate a port'));
        else resolve(port);
      });
    });
  });
}

function stripAddedSignalHandlers(before: {
  SIGINT: readonly NodeJS.SignalsListener[];
  SIGTERM: readonly NodeJS.SignalsListener[];
}): void {
  for (const signal of ['SIGINT', 'SIGTERM'] as const) {
    for (const listener of process.listeners(signal)) {
      if (!before[signal].includes(listener)) {
        process.removeListener(signal, listener);
      }
    }
  }
}

export interface AppiumServerHandle {
  readonly port: number;
  close(): Promise<void>;
}

export interface StartServerOptions {
  readonly homeDir: string;
  readonly driverPackages: readonly string[];
  readonly logFile: string;
  readonly logger: Logger;
  /** Appium 3 scoped syntax, e.g. 'uiautomator2:adb_shell'. */
  readonly allowInsecure?: readonly string[];
}

export async function startAppiumServer(options: StartServerOptions): Promise<AppiumServerHandle> {
  prepareAppiumHome(options.homeDir, options.driverPackages);
  mkdirSync(dirname(options.logFile), { recursive: true });

  // Import-safety rule (ADR-0001 §5.5): appium loads HERE, never at top level.
  // Non-literal specifier: appium ships raw .ts type sources that explode under
  // strict verbatimModuleSyntax; we type the surface we use by hand instead.
  const appiumSpecifier = 'appium';
  // The package is CJS — named ESM imports fail; use the default namespace.
  const appiumModule = (await import(appiumSpecifier)) as unknown as {
    default?: { main: (args: Record<string, unknown>) => Promise<unknown> };
    main?: (args: Record<string, unknown>) => Promise<unknown>;
  };
  const main = appiumModule.default?.main ?? appiumModule.main;
  if (!main) {
    throw new KrakenError('KRK-DRIVER-START-FAILED', 'appium package has no main() export.');
  }

  // Allocate AFTER the (slow, seconds-cold) appium import so the port-reuse
  // race window stays microseconds — appium process.exit(1)s on EADDRINUSE.
  const port = await allocatePort();

  // Hazard 2: strip the SIGINT/SIGTERM handlers main() installs.
  const before = {
    SIGINT: process.listeners('SIGINT'),
    SIGTERM: process.listeners('SIGTERM'),
  };

  options.logger.info('starting embedded Appium server', {
    port,
    home: options.homeDir,
    logFile: options.logFile,
  });
  let server: { close(): Promise<void> };
  try {
    server = (await main({
      subcommand: 'server',
      port,
      address: '127.0.0.1',
      appiumHome: options.homeDir,
      throwInsteadOfExit: true,
      // Quiet console (the TUI owns stdout), full debug into the log file.
      loglevel: 'error:debug',
      logFile: options.logFile,
      ...(options.allowInsecure !== undefined ? { allowInsecure: [...options.allowInsecure] } : {}),
    })) as { close(): Promise<void> };
  } catch (cause) {
    stripAddedSignalHandlers(before);
    throw KrakenError.wrap(cause, 'KRK-DRIVER-START-FAILED', 'embedded Appium failed to start');
  }
  // Appium registers its handlers in a continuation AFTER main() resolves
  // (live-verified) — wait one macrotask before stripping.
  await new Promise((resolve) => setImmediate(resolve));
  stripAddedSignalHandlers(before);

  options.logger.info('Appium server ready', { port });
  return {
    port,
    close: async () => {
      await server.close();
      options.logger.info('Appium server stopped', { port });
    },
  };
}
